### ISSUE TITLE
waybar and background doesnt show up

### ISSUE THREAD

**Issue by kartoffelkopp89** [1882COYS/1882-dots#1]
sddm and the desktop just show a dark grey background and nothing else (no waybar etc...) i can use kitty and other applications normally.
![20231230_221041](https://github.com/1882COYS/1882-dots/assets/155265916/4f85aa75-6af9-4712-a28f-6f1c90aeda3e)
![20231230_221120](https://github.com/1882COYS/1882-dots/assets/155265916/eece3645-d527-4009-993f-d4b593c4926f)

**Comment by kartoffelkopp89** [comment]
im sorry if its trivial, im new to arch :)

**Comment by 1882COYS** [comment]
Hi. It looks like something went wrong with the install script, try running it again and looking for errors, make sure to delete the 1882-dots file.

---

After retrying, run these commands and make sure you have no errors:

```
pacman -Qq neofetch thunar dunst kvantum rofi swaylock waybar wofi ccache qt6ct qt6-wayland qt5-graphicaleffects qt5-svg qt5-quickcontrols2 zsh firefox kitty swaybg brightnessctl pamixer 
```

```
yay -Qm hyprland-git nwg-look wlogout picom ttf-jetbrains-mono-nerd catppuccin-gtk-theme-macchiato papirus-folders sddm-git 
```

If you have an error on the first command, download that package from pacman. The second one wont throw you an error, so make sure all the packages on the command are listed, if they are not, install from yay.

---

Next, open a terminal and run:

```
Hyprland
```

If this looks correct ( Apart from being zoomed in on some occasions ) It is an issue with sddm login.  You can try switch between login managers and see if any work.

**Comment by lwilk0** [comment]
Sorry this was an issue with my install script, please delete it and the 1882-dots folder from your pc and start over, making sure to select yes  every time prompted (apart from when asked to remove make dependencies) . Thank you for your patience.

Note, before running the script, remove ~/Pictures

There is also an issue on some laptops where waybar wont start when booting into hyprland. Try running it from terminal to make sure that it is actually working,  this is a problem with waybar itself and not my dotfiles.
