### ISSUE TITLE
waybar not start

### ISSUE THREAD

**Issue by kinjar1988** [1882COYS/1882-dots#2]
Hi, I install your dotfiles successfully. After installation SDDM not work. I have only ttf mode to login. Also nothing display on screen. waybar not start.  when I type waybar in terminal error showing that " in line number 113 colum 5 " , " or " } " missing. I installed in endevoursos with nodesktop.

**Comment by lwilk0** [comment]
Hello, the waybar issue should now be fixed. There are quite a few issues on Linux 6.7, so please use 6.9.9 otherwise you will get the issues you described

**Comment by kinjar1988** [comment]
It's works but now another issue for pamac (Package Manager). Authentication failed. Actually no authentication window showing. 
One more query about theme how can I change pamac theme to dark mode.

**Comment by lwilk0** [comment]
Hi, for your pamac issue you will need to research it as I don't use it and cant help you with it. To fix the theme you can look at the catppuccin github page to see if you can change it. The theme used is cattpuccin macchiato blue
